
version: '3.7'

x-env-defaults: &env
  NODE_ENV: development
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.15-alpine
  working_dir: /ticket-to-ride
  restart: always
  volumes:
    - .:/ticket-to-ride:cached
    - ./node_modules:/ticket-to-ride/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  api:
    <<: *node
    working_dir: /ticket-to-ride/api
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      APP_URL: ${APP_URL-http://0.0.0.0:27981}
      MONGO_URI: ${MONGO_URI-mongodb://root:password123@mongodb-primary:27017,mongodb-secondary:27017?replicaSet=tickettoride&authSource=admin&readPreference=primary}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      TOKEN_SECRET: ${TOKEN_SECRET-thisisntsecretandyoushouldusesomethingdifferentinproductiondawg}
    depends_on:
      - mongodb-secondary
    ports:
      - "27980:27980"

  app:
    <<: *node
    working_dir: /ticket-to-ride/app
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      VUE_APP_GRAPHQL_URL: ${VUE_APP_GRAPHQL_URL-http://0.0.0.0:27980/graphql}
    depends_on:
      - api
    ports:
      - "27981:27981"

  mongodb-primary:
    image: bitnami/mongodb:4.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=tickettoride
    volumes:
      - mongodb-primary:/bitnami
    ports:
      - "27979:27017"

  mongodb-secondary:
    image: bitnami/mongodb:4.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=tickettoride
    volumes:
      - mongodb-secondary:/bitnami

volumes:
  yarn-cache: {}
  mongodb-primary: {}
  mongodb-secondary: {}
